### ISSUE TITLE
QA/QC

### ISSUE THREAD

**Issue by atredennick** [atredennick/prodDiv#1]
@pbadler Can you take a look at https://github.com/atredennick/prodDiv/blob/master/analysis/nutnet_glmm_analysis.R to make sure it is right? Specifically, take a look at the nested random effects. I am pretty sure it is right, but I am always worried about these.

Also take a look at the Fraser global-extent analysis (first ~50 lines of that script).

If you run the code you will likely get warnings about convergence. This is a well-known issue with lme4 https://github.com/lme4/lme4/issues/120. I tested a bunch of different optimizers and got the same results, meaning we should be in the clear. I am also running a Bayesian version just to make sure we get consistent results.

**Comment by pbadler** [comment]
The Fraser one looks ok, as long as "pi" really means "site." No PI 
surveyed more than one site? The number of observations for each random 
effect look sensible.

Your NutNet code had a problem I think. The site/block part wasn't 
working right--if you look at the # observations on the random effects, 
you see that only 6 block effects were fit. I used this code. I think 
this looks better.

good.data$siteblock <-paste(good.data$site,good.data$block,sep="") # 
make an explicit block within site factor

## Global quadratic fit

# Write model formula

mod.formula <- 
as.formula(richness~logbiomass+I(logbiomass^2)+(1|site/siteblock)) #( 
1|site) +(1|siteblock))

# mod.formula <- as.formula(richness~logbiomass+I(logbiomass^2)+(

1|site) +(1|siteblock)) # same result

On 10/4/2015 7:03 AM, Andrew Tredennick wrote:

> @pbadler https://github.com/pbadler Can you take a look at 
> https://github.com/atredennick/prodDiv/blob/master/analysis/nutnet_glmm_analysis.R 
> to make sure it is right? Specifically, take a look at the nested 
> random effects. I am pretty sure it is right, but I am always worried 
> about these.
> 
> Also take a look at the Fraser global-extent analysis (first ~50 lines 
> of that script).
> 
> If you run the code you will likely get warnings about convergence. 
> This is a well-known issue with lme4 lme4/lme4#120 
> https://github.com/lme4/lme4/issues/120. I tested a bunch of 
> different optimizers and got the same results, meaning we should be in 
> the clear. I am also running a Bayesian version just to make sure we 
> get consistent results.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/atredennick/prodDiv/issues/1.

## 

Peter Adler
Dept. Wildland Resources and the Ecology Center
Utah State University
http://www.cnr.usu.edu/htm/facstaff/adler-web
